"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Columns3, Activity, ShieldCheck, Clock3, CircleHelp, ExternalLink } from "lucide-react";
import { categories, parseIntent, rankAgents, type RankedAgent, type Agent } from "@/lib/domain";
import { api, CategoryIcon, dateLabel, ErrorNotice, shortAddress, SourceLink, TrustBadge } from "./ui";
import { useMarket } from "./shell";
import { EvidenceStatus } from "./evidence-status";
import { SaveAgent } from "./profile";
import { Activation } from "./activation";
export function AgentDetail({ id }: { id: string }) {
  const [match, setMatch] = useState<RankedAgent | null>(null); const [agent, setAgent] = useState<Agent | null>(null); const [error, setError] = useState(""); const { toggleCompare, compared } = useMarket();
  useEffect(() => { const controller = new AbortController(); api<Agent>(`/api/agents/${encodeURIComponent(id)}`, { signal: controller.signal }).then(a => { setAgent(a); try { const q = sessionStorage.getItem("agentmarket-intent"); if (q) setMatch(rankAgents([a], parseIntent(q))[0] ?? null); } catch { /* No stored intent. */ } }).catch(e => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [id]);
  if (error) return <div className="page"><Link className="back-link" href="/">← Marketplace</Link><ErrorNotice message={error} /></div>;
  if (!agent) return <div className="page" aria-busy="true"><div className="detail-skeleton" /></div>;
  const cat = agent.categories[0] ?? "yield";
  const category = agent.categories[0]; const categoryLabel = category ? categories.find(c => c.id === category)?.name : "Unclassified registry identity";
  return <div className="page detail-page"><Link className="back-link" href={category ? `/category/${category}` : "/?catalog=registry"}><ArrowLeft size={15} />{categoryLabel}</Link><div className="detail-header"><SaveAgent id={id} name={agent.name} /><span className={`agent-avatar large ${cat}`}><CategoryIcon category={cat} size={36} /></span><div><div className="eyebrow small">INDEPENDENT AGENT · BNB CHAIN</div><h1>{agent.name}</h1><div className="detail-badges"><TrustBadge verified={agent.verified} /><span className="badge subtle">{agent.active === true ? "Publisher marked active" : agent.active === false ? "Publisher marked inactive" : "Availability not confirmed"}</span></div></div><button className="button" onClick={() => toggleCompare(agent)}><Columns3 size={16} />{compared.some(a => a.id === id) ? "Added to comparison" : "Compare agent"}</button></div>
    <div className="detail-grid"><div className="detail-content"><section><h2>Meet your next specialist.</h2><p className="description-full">{agent.description}</p><small className="source-note">Description and capabilities are publisher claims. They have not been independently audited.</small></section>{match && <section><h2>Why this may fit your search</h2><ul className="match-reasons">{match.reasons.map(r => <li key={r}>{r}</li>)}</ul>{match.missing.length > 0 && <div className="notice"><CircleHelp size={18} /><div><strong>Compatibility is not confirmed</strong><p>{match.missing.join(". ")}.</p></div></div>}<small>Rules determine relevance from source evidence. A ranking is not an investment recommendation.</small></section>}<section><h2>What it brings to the table</h2><div className="capability-grid">{agent.categories.map(c => <div key={c}><CategoryIcon category={c} /><strong>{categories.find(x => x.id === c)?.name}</strong><p>{categories.find(x => x.id === c)?.description}</p></div>)}</div><dl className="detail-facts"><div><dt>Assets mentioned</dt><dd>{agent.assets.join(", ") || "Not available"}</dd></div><div><dt>Protocols mentioned</dt><dd>{agent.protocols.join(", ") || "Not available"}</dd></div><div><dt>Execution interfaces</dt><dd>{agent.interfaces.join(", ") || "Not available"}</dd></div><div><dt>Best for</dt><dd>{category ? `Users evaluating ${categoryLabel?.toLowerCase()} services.` : "Users inspecting a registry identity before trusting its service claims."}</dd></div></dl></section>
      <EvidenceStatus agent={agent} /><section><div className="section-title"><ShieldCheck size={20} /><h2>Evidence you can inspect</h2></div><div className="evidence-grid"><div><span>Identity</span><strong>{agent.verified ? "Source verified" : agent.registered ? "Registered onchain" : "Publisher endpoint"}</strong><p>{agent.verified ? "8004scan reports this identity as verified." : "Registration proves an identity exists. It is not an endorsement."}</p></div><div><span>Reputation</span><strong>{agent.feedbackCount ?? "—"} <small>feedback records</small></strong><p>{agent.feedbackAverage !== null ? `Source average: ${agent.feedbackAverage}. See the source for scoring methodology.` : "No scored feedback is available. A missing record is not a positive rating."}</p></div></div><SourceLink href={agent.sourceUrl}>Inspect identity and feedback at the source</SourceLink></section>
      <section><div className="section-title"><Activity size={20} /><h2>Performance & activity</h2></div><div className="notice subtle-notice"><CircleHelp size={19} /><div><strong>Performance data is not available.</strong><p>This source does not provide independently verified returns or strategy execution history. Request a report with a measurement period, source and timestamp.</p></div></div>{agent.registrationTx && <div className="activity-line"><span className="timeline-dot" /><div><strong>Agent identity registered</strong><p>This is an identity event, not proof of strategy execution.</p></div><SourceLink href={`https://bscscan.com/tx/${agent.registrationTx}`}>Transaction</SourceLink></div>}<dl className="detail-facts"><div><dt>Registry updated</dt><dd>{dateLabel(agent.updatedAt)}</dd></div><div><dt>Retrieved</dt><dd>{dateLabel(agent.fetchedAt)}</dd></div></dl></section>
      <section><h2>Understand the risk</h2><p>An independent risk assessment is not available. Publisher descriptions may omit smart-contract, liquidity, market, counterparty and liquidation risks. Research output needs your review before you act on it.</p><p>Agent identity and feedback do not guarantee an outcome or protect against losses.</p></section>
      <details className="technical"><summary>Identity, provenance and technical details</summary><dl className="detail-facts"><div><dt>Source</dt><dd>{agent.source}</dd></div><div><dt>Network</dt><dd>BNB Smart Chain (56)</dd></div><div><dt>Owner</dt><dd>{agent.owner ? <SourceLink href={`https://bscscan.com/address/${agent.owner}`}>{shortAddress(agent.owner)}</SourceLink> : "Not available"}</dd></div><div><dt>Registry reference</dt><dd>{agent.tokenId || "Not registered"}</dd></div></dl>{agent.endpoint && <SourceLink href={agent.endpoint}>Published agent card</SourceLink>}</details>
    </div><aside className="activation-panel"><div className="eyebrow small">FROM DISCOVERY TO ACTION</div><h2>The next step,<br />on your terms.</h2><p>Request a live quote, understand the scope and approve only what you need.</p><div className="activation-summary"><div><ShieldCheck size={17} /><span>Verified seller quote before payment</span></div><div><Clock3 size={17} /><span>Limited, expiring permissions</span></div><div><Activity size={17} /><span>Onchain status and delivery tracking</span></div></div><Activation agent={agent} />{agent.website && <a className="button full" href={agent.website} target="_blank" rel="noopener noreferrer">Open provider <ExternalLink size={14} /></a>}<div className="panel-footnote">Compatible sellers can be hired here. Other agents must publish a supported activation interface first.</div></aside></div>
  </div>;
}
