"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, Search, Sparkles, SlidersHorizontal, RefreshCw, ShieldCheck, Check, Plus, Columns3, ChevronLeft, ChevronRight, CircleHelp } from "lucide-react";
import { categories, assets, protocols, type Category, type Intent, type RankedAgent } from "@/lib/domain";
import { useMarket } from "./shell";
import { api, CategoryIcon, dateLabel, ErrorNotice, TrustBadge } from "./ui";
import { SaveAgent } from "./profile";
import { MarketContext } from "./market-context";
type Discovery = { agents: RankedAgent[]; total: number; compatible: number; counts: Record<Category, number>; warnings: string[]; fetchedAt: string; pages: number; scope: string; intent: Intent };
export function AgentCard({ agent, category }: { agent: RankedAgent; category?: Category }) {
  const { compared, toggleCompare } = useMarket(); const selected = compared.some(a => a.id === agent.id); const cat = category ?? agent.categories[0] ?? "yield";
  return <article className="agent-card"><div className="agent-card-top"><SaveAgent id={agent.id} name={agent.name} /><span className={`agent-avatar ${cat}`}><CategoryIcon category={cat} size={25} /></span><button className={`compare-toggle ${selected ? "selected" : ""}`} onClick={() => toggleCompare(agent)} aria-label={`${selected ? "Remove" : "Compare"} ${agent.name}`} aria-pressed={selected}>{selected ? <Check size={16} /> : <Plus size={16} />}</button></div><div className="agent-title"><Link href={`/agents/${agent.id}`}>{agent.name}</Link></div><div className="agent-byline">{categories.find(c => c.id === cat)?.name}<span>·</span>BNB Chain</div><p className="agent-description">{agent.description}</p><div className="agent-badges"><TrustBadge verified={agent.verified} />{agent.interfaces.includes("A2A") && <span className="badge subtle">Agent-to-agent</span>}</div><dl className="card-facts"><div><dt>Feedback records</dt><dd>{agent.feedbackCount ?? "Not available"}</dd></div><div><dt>Risk assessment</dt><dd className="muted">Not available</dd></div></dl><div className="card-tags">{(agent.protocols.length ? agent.protocols : ["Protocol not specified"]).slice(0, 2).map(p => <span key={p}>{p}</span>)}{agent.assets.slice(0, 2).map(p => <span key={p}>{p}</span>)}</div><div className="card-bottom"><span>{agent.pricing ?? "Quote before you pay"}</span><Link href={`/agents/${agent.id}`} aria-label={`View ${agent.name}`}>View agent <ArrowUpRight size={15} /></Link></div></article>;
}
export function Marketplace({ category }: { category?: Category }) {
  const [query, setQuery] = useState(""); const [submitted, setSubmitted] = useState(""); const [asset, setAsset] = useState(""); const [protocol, setProtocol] = useState(""); const [risk, setRisk] = useState(""); const [verified, setVerified] = useState(false); const [page, setPage] = useState(1);
  const [data, setData] = useState<Discovery | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [filters, setFilters] = useState(false); const [refresh, setRefresh] = useState(0);
  const [ready, setReady] = useState(false); const [shareMessage, setShareMessage] = useState(""); const [sort, setSort] = useState("relevance");
  useEffect(() => {
    const restore = () => { const p = new URLSearchParams(location.search); setQuery(p.get("q")?.slice(0, 500) || ""); setSubmitted(p.get("q")?.slice(0, 500) || ""); setAsset(p.get("asset") || ""); setProtocol(p.get("protocol") || ""); setRisk(p.get("risk") || ""); setVerified(p.get("verified") === "true"); setPage(Math.max(1, Math.min(100, Math.floor(Number(p.get("page")) || 1)))); setSort(p.get("sort") || "relevance"); setReady(true); setLoading(true); };
    const timer = setTimeout(restore, 0); window.addEventListener("popstate", restore); return () => { clearTimeout(timer); window.removeEventListener("popstate", restore); };
  }, [category]);
  async function shareFilters() { try { await navigator.clipboard.writeText(location.href); setShareMessage("Search link copied. Your submitted search is included; review it before sharing."); } catch { setShareMessage(location.href); } }
  const cat = categories.find(c => c.id === category);
  const load = useCallback((signal: AbortSignal) => {
    const params = new URLSearchParams({ q: submitted, page: String(page), sort, asset, protocol, risk, verified: String(verified), ...(category ? { category } : {}) });
    const visible = new URLSearchParams(params); visible.delete("category"); for (const [key, value] of [...visible]) if (!value || value === "false" || (key === "page" && value === "1") || (key === "sort" && value === "relevance")) visible.delete(key);
    history.replaceState(null, "", location.pathname + (visible.size ? `?${visible}` : ""));
    api<Discovery>(`/api/discover?${params}`, { signal }).then(result => { if (signal.aborted) return; setData(result); setError(""); try { sessionStorage.setItem("agentmarket-intent", result.intent.query); } catch { /* Search still works without storage. */ } }).catch(e => { if (!signal.aborted) { setData(null); setError(e.message); } }).finally(() => { if (!signal.aborted) setLoading(false); });
  }, [submitted, page, sort, asset, protocol, risk, verified, category]);
  useEffect(() => { if (!ready) return; const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load, refresh, ready]);
  function search(text = query) { setLoading(true); setSubmitted(text); setQuery(text); setPage(1); setRefresh(v => v + 1); }
  function changeFilter(action: () => void) { setLoading(true); setPage(1); action(); setRefresh(v => v + 1); }
  return <div className="page marketplace-page">
    <section className={`hero ${category ? "category-hero" : ""}`}><div className="hero-content"><div className="eyebrow"><span />{cat ? "SPECIALISTS FOR YOUR STRATEGY" : "THE AGENT MARKETPLACE"}</div><h1>{cat ? cat.name : <>Find the right agent.<br /><em>Make your next move.</em></>}</h1><p>{cat ? cat.description : "A little expertise goes a long way. Discover real AI agents, compare the evidence, and put the right one to work."}</p></div>{!category && <div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="art-core"><LayersMark /></div><span className="orbit-node node-one"><CategoryIcon category="rebalancing" /></span><span className="orbit-node node-two"><CategoryIcon category="grid" /></span><span className="orbit-node node-three"><CategoryIcon category="yield" /></span><span className="orbit-node node-four"><CategoryIcon category="health" /></span><span className="art-caption">YOUR INTENT. CONNECTED.</span></div>}</section>
    <section className="search-section" aria-label="Find an agent"><form className="search-box" onSubmit={e => { e.preventDefault(); search(); }}><Sparkles size={22} className="search-sparkle" /><label className="sr-only" htmlFor="intent-search">What would you like an agent to do?</label><input id="intent-search" value={query} onChange={e => setQuery(e.target.value)} maxLength={500} placeholder="What would you like an agent to do?" /><button className="button primary" type="submit">Find my agent <ArrowRight size={17} /></button></form><div className="search-suggestions"><span>Try asking</span>{["Find USDT yield agents", "Manage my LP position", "Protect my lending position"].map(text => <button key={text} onClick={() => search(text)}>{text}<ArrowUpRight size={12} /></button>)}</div></section>
    {!category && <section className="category-section"><div className="section-heading"><h2>A specialist for every strategy</h2><span>Four ways to get ahead</span></div><div className="category-grid">{categories.map(c => <Link className={`category-tile ${c.id}`} key={c.id} href={`/category/${c.id}`}><div className="category-tile-top"><span className="category-icon"><CategoryIcon category={c.id} size={24} /></span><ArrowUpRight size={16} /></div><h3>{c.name}</h3><p>{c.short}</p><div className="category-count">{data ? `${data.counts[c.id] ?? 0} discovered agents` : "Explore category"}<ArrowRight size={13} /></div></Link>)}</div></section>}
    <section className="results-section" aria-labelledby="results-title"><div className="section-heading results-heading"><div><div className="eyebrow small">EXPERTISE, WITH EVIDENCE</div><h2 id="results-title">{submitted ? "Agents for your next move" : cat ? `${cat.name} agents` : "Explore the marketplace"}{data && <span className="result-count">{data.total}</span>}</h2></div><button className={`button filter-button ${filters ? "pressed" : ""}`} onClick={() => setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={16} />Filters{(asset || protocol || risk || verified) && <span className="network-dot" />}</button></div>
      <div className="results-toolbar"><div className="tabs"><button className={!verified ? "selected" : ""} onClick={() => changeFilter(() => setVerified(false))}>All agents</button><button className={verified ? "selected" : ""} onClick={() => changeFilter(() => setVerified(true))}><ShieldCheck size={14} />Verified identities</button></div><div className="sort-note"><label className="sr-only" htmlFor="agent-sort">Sort agents</label><select id="agent-sort" value={sort} onChange={e => changeFilter(() => setSort(e.target.value))}><option value="relevance">Relevance</option><option value="updated">Recently updated</option><option value="feedback">Feedback count</option></select><button className="text-button" onClick={shareFilters}>Share filters</button><button className="icon-button" aria-label="Refresh agents" onClick={() => { setLoading(true); setRefresh(v => v + 1); }}><RefreshCw size={15} className={loading ? "spin" : ""} /></button></div></div>
      {shareMessage && <p role="status">{shareMessage}</p>}{filters && <div className="filter-row"><label>Asset<select aria-label="Asset" value={asset} onChange={e => changeFilter(() => setAsset(e.target.value))}><option value="">Any asset</option>{assets.map(a => <option key={a}>{a}</option>)}</select></label><label>Protocol<select aria-label="Protocol" value={protocol} onChange={e => changeFilter(() => setProtocol(e.target.value))}><option value="">Any protocol</option>{protocols.map(a => <option key={a}>{a}</option>)}</select></label><label>Risk preference<select aria-label="Risk preference" value={risk} onChange={e => changeFilter(() => setRisk(e.target.value))}><option value="">Any / unknown</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><button className="text-button" onClick={() => changeFilter(() => { setAsset(""); setProtocol(""); setRisk(""); setVerified(false); })}>Reset filters</button></div>}
      {data && submitted && <div className="intent-summary"><Search size={18} /><div><strong>{data.intent.category ? categories.find(c => c.id === data.intent.category)?.name : "Agent search"}{data.intent.assets.length > 0 ? ` · ${data.intent.assets.join(", ")}` : ""}{data.intent.risk !== "unknown" ? ` · ${data.intent.risk} risk requested` : ""}</strong><p>{data.compatible} compatible results. {data.total - data.compatible} related agents need more evidence.{data.intent.amount ? ` Budget context: ${data.intent.amount.toLocaleString("en-US")}.` : ""}</p></div><span className="badge subtle">{data.intent.method === "language-model" ? "Intent understood" : "Keyword interpretation"}</span></div>}
      {data && !loading && data.compatible === 0 && data.total > 0 && <div className="notice"><CircleHelp size={18} /><div><strong>No agent meets every requirement yet.</strong><p>The related agents below have missing compatibility or risk information. They are not confirmed matches. Review the evidence before deciding.</p></div></div>}
      {error && <ErrorNotice message={error} />}{data?.warnings.map(w => <div key={w} className="notice">{w}</div>)}
      {loading ? <div className="agent-grid" aria-label="Loading agents" aria-busy="true">{Array.from({ length: 6 }, (_, i) => <div key={i} className="agent-skeleton"><div /><div /><div /><div /></div>)}</div> : data?.agents.length ? <div className="agent-grid">{data.agents.map(agent => <AgentCard key={agent.id} agent={agent} category={category} />)}</div> : <div className="empty"><Search size={32} /><h3>{error ? "Discovery is temporarily unavailable" : "A more specific search deserves more evidence."}</h3><p>{error ? "Refresh to reconnect to the live registry." : "No registered agents match these filters in the current discovery window. Try another category or remove a filter."}</p><button className="button" onClick={() => { setAsset(""); setProtocol(""); setRisk(""); setVerified(false); search(""); }}>Reset search</button></div>}
      {data && !loading && <div className="results-footer"><span>Source: 8004scan · Retrieved {dateLabel(data.fetchedAt)}<small>{data.scope}</small></span><div className="pagination"><button className="icon-button" aria-label="Previous page" disabled={page <= 1} onClick={() => { setLoading(true); setPage(p => p - 1); }}><ChevronLeft size={17} /></button><span>{page} / {Math.max(1, data.pages)}</span><button className="icon-button" aria-label="Next page" disabled={page >= data.pages} onClick={() => { setLoading(true); setPage(p => p + 1); }}><ChevronRight size={17} /></button></div></div>}
    </section>
    <MarketContext />
    <section className="trust-strip"><ShieldCheck size={26} /><div><h3>Good decisions start with clear information.</h3><p>Identity, publisher claims and investment risk are different things. We keep them separate.</p></div><Link href="/compare">Compare the evidence <Columns3 size={16} /></Link></section>
  </div>;
}
function LayersMark() { return <svg width="76" height="76" viewBox="0 0 76 76" fill="none"><path d="M38 11 65 27 38 43 11 27 38 11Z" fill="#DCEAC5" /><path d="m11 38 27 16 27-16M11 49l27 16 27-16" stroke="#DCEAC5" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
