"use client";
import { useState } from "react";
import { ArrowUpRight, RefreshCw, Search } from "lucide-react";
import { api, dateLabel, ErrorNotice, SourceLink } from "./ui";
type Snapshot = { price: number; pool: string; feePercent: number; wbnbBalance: string; usdtBalance: string; blockNumber: string; timestamp: string; source: string; note: string };
type Security = { content: string; observedAt: string; source: string; sourceUrl: string; note: string };
export function MarketContext() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [token, setToken] = useState(""); const [security, setSecurity] = useState<Security | null>(null); const [securityError, setSecurityError] = useState(""); const [securityBusy, setSecurityBusy] = useState(false);
  async function refresh() { setBusy(true); setError(""); try { setSnapshot(await api<Snapshot>("/api/market")); } catch { setError("Live pool data is temporarily unavailable. Try refreshing."); } finally { setBusy(false); } }
  async function checkToken() { setSecurityBusy(true); setSecurityError(""); setSecurity(null); try { setSecurity(await api<Security>(`/api/research/security?token=${encodeURIComponent(token)}`)); } catch (e) { setSecurityError((e as Error).message); } finally { setSecurityBusy(false); } }
  return <section className="market-context"><div className="section-heading"><div><div className="eyebrow small">LOOK BEFORE YOU ACT</div><h2>Context for your next conversation</h2></div><button className="button" onClick={refresh} disabled={busy}><RefreshCw size={14} className={busy ? "spin" : ""} />{snapshot ? "Refresh live data" : "Read live pool data"}</button></div><p>Research a PancakeSwap pool before asking an agent to manage your liquidity or design a strategy.</p>{error && <ErrorNotice message={error} />}{snapshot && <><div className="market-data"><div><span>PancakeSwap v3</span><strong>WBNB / USDT</strong></div><div><span>Pool spot price</span><strong>{snapshot.price.toLocaleString("en-US", { maximumFractionDigits: 2 })} <small>USDT / WBNB</small></strong></div><div><span>Pool fee tier</span><strong>{snapshot.feePercent}%</strong></div></div><dl className="detail-facts"><div><dt>Token balances in pool</dt><dd>{Number(snapshot.wbnbBalance).toLocaleString("en-US", { maximumFractionDigits: 2 })} WBNB · {Number(snapshot.usdtBalance).toLocaleString("en-US", { maximumFractionDigits: 0 })} USDT</dd></div><div><dt>Observed block</dt><dd>{snapshot.blockNumber} · {dateLabel(snapshot.timestamp)}</dd></div></dl><small>{snapshot.note}</small><div style={{ marginTop: 12 }}><SourceLink href={snapshot.source}>Inspect pool onchain</SourceLink></div></>}<details className="technical"><summary>Research a token’s published security findings</summary><p>A read-only check through the connected research service. Findings do not establish that a token or agent is safe.</p><form className="token-search" onSubmit={e => { e.preventDefault(); void checkToken(); }}><label className="sr-only" htmlFor="token-address">BNB Chain token address</label><input id="token-address" value={token} onChange={e => setToken(e.target.value)} placeholder="BNB Chain token address (0x…)" pattern="0x[a-fA-F0-9]{40}" required /><button className="button" disabled={securityBusy}><Search size={14} />Check token</button></form>{securityError && <ErrorNotice message={securityError} />}{security && <><pre>{security.content}</pre><small>{security.note} · {dateLabel(security.observedAt)}</small><SourceLink href={security.sourceUrl}>{security.source} <ArrowUpRight size={13} /></SourceLink></>}</details></section>;
}
