"use client";
import { useEffect, useState } from "react";
import { api, ErrorNotice, SourceLink } from "./ui";
type Resource = { slug: string; method: string; description: string; pricing?: { amount?: string; asset: string; network: string } };
type Terms = { accepts: { network: string; asset: string; payTo: string; amount?: string; maxAmountRequired?: string }[]; observedAt: string };
export function XonaServices() {
  const [resources, setResources] = useState<Resource[]>([]); const [selected, setSelected] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [terms, setTerms] = useState<Terms | null>(null);
  useEffect(() => { const c = new AbortController(); api<{ resources: Resource[] }>("/api/xona", { signal: c.signal }).then(r => { setResources(r.resources); setSelected(r.resources[0]?.slug ?? ""); }).catch(e => { if (!c.signal.aborted) setError(e.message); }); return () => c.abort(); }, []);
  const resource = resources.find(r => r.slug === selected);
  async function preview() { setBusy(true); setError(""); setTerms(null); try { setTerms(await api<Terms>("/api/xona", { method: "POST", body: JSON.stringify({ slug: selected }) })); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section className="xona-services"><h3>Xona services</h3><p>Xona uses pay-per-request x402 services. These follow the provider&apos;s payment flow rather than a research escrow job.</p><label className="field-label">Choose a service<select value={selected} onChange={e => { setSelected(e.target.value); setTerms(null); }}>{resources.map(r => <option key={r.slug} value={r.slug}>{r.slug}</option>)}</select></label><p>{resource?.description}</p>{resource?.pricing && <p>Published price: {resource.pricing.amount ?? "Variable"} {resource.pricing.asset} · {resource.pricing.network}</p>}<button className="button full" disabled={busy || !resource || resource.method !== "POST"} onClick={preview}>{busy ? "Checking requirements…" : "Check payment requirements"}</button><small>This unsigned check makes no payment and creates no Altana permission.</small>{terms && <div className="notice"><div><strong>Live payment requirements received</strong>{terms.accepts.map((t, i) => <p key={i}>Network: {t.network}<br />Token: {t.asset}<br />Amount in token base units: {t.amount ?? t.maxAmountRequired}<br />Recipient: {t.payTo}</p>)}<p>Payment and delivery through this x402 route are not yet supported inside Binera. Use Xona directly and review its supported wallet and network.</p></div></div>}{error && <ErrorNotice message={error} />}<SourceLink href="https://xona-agent.com/">Open Xona</SourceLink><p><SourceLink href="https://api.xona-agent.com/openapi.json">Provider API documentation</SourceLink></p></section>;
}
